export const GangTaskName = {
  UNASSIGNED: 'Unassigned',
  MUG_PEOPLE: 'Mug People',
  DEAL_DRUGS: 'Deal Drugs',
  STRONGARM_CIVILIANS: 'Strongarm Civilians',
  RUN_A_CON: 'Run a Con',
  ARMED_ROBBERY: 'Armed Robbery',
  TRAFFICK_ILLEGAL_ARMS: 'Traffick Illegal Arms',
  THREATEN_AND_BLACKMAIL: 'Threaten & Blackmail',
  HUMAN_TRAFFICKING: 'Human Trafficking',
  TERRORISM: 'Terrorism',
  VIGILANTE_JUSTICE: 'Vigilante Justice',
  TRAIN_COMBAT: 'Train Combat',
  TRAIN_HACKING: 'Train Hacking',
  TRAIN_CHARISMA: 'Train Charisma',
  TERRITORY_WARFARE: 'Territory Warfare',
};

export const GANG_EQUIPMENT_NAME_TO_TYPE_MAP = {
  'Baseball Bat': 'Weapon',
  Katana: 'Weapon',
  'Glock 18C': 'Weapon',
  P90C: 'Weapon',
  'Steyr AUG': 'Weapon',
  'AK-47': 'Weapon',
  'M15A10 Assault Rifle': 'Weapon',
  'AWM Sniper Rifle': 'Weapon',
  'Bulletproof Vest': 'Armor',
  'Full Body Armor': 'Armor',
  'Liquid Body Armor': 'Armor',
  'Graphene Plating Armor': 'Armor',
  'Ford Flex V20': 'Vehicle',
  'ATX1070 Superbike': 'Vehicle',
  'Mercedes-Benz S9001': 'Vehicle',
  'White Ferrari': 'Vehicle',
  'NUKE Rootkit': 'Rootkit',
  'Soulstealer Rootkit': 'Rootkit',
  'Demon Rootkit': 'Rootkit',
  'Hmap Node': 'Rootkit',
  'Jack the Ripper': 'Rootkit',
  'Bionic Arms': 'Augmentation',
  'Bionic Legs': 'Augmentation',
  'Bionic Spine': 'Augmentation',
  BrachiBlades: 'Augmentation',
  'Nanofiber Weave': 'Augmentation',
  'Synthetic Heart': 'Augmentation',
  'Synfibril Muscle': 'Augmentation',
  BitWire: 'Augmentation',
  Neuralstimulator: 'Augmentation',
  DataJack: 'Augmentation',
  'Graphene Bone Lacings': 'Augmentation',
};

export const GANG_MEMBER_NAMES = [
  'Ace',
  'Blaze',
  'Bullet',
  'Diablo',
  'Frost',
  'Fury',
  'Ghost',
  'Havoc',
  'Hunter',
  'Jinx',
  'Kraken',
  'Phantom',
  'Raze',
  'Razor',
  'Reaper',
  'Serpent',
  'Shadow',
  'Titan',
  'Venom',
  'Viper',
  'Wolf',
];
